"""removed UniqueConstraint

Revision ID: 5b9c95d33c91
Revises: f9244536033a
Create Date: 2025-07-07 14:18:11.276657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b9c95d33c91'
down_revision = 'f9244536033a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_bucket_file'), 'files', type_='unique')
    op.drop_column('files', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uix_bucket_file'), 'files', ['bucket_name', 'file_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
