"""unique columns

Revision ID: f9244536033a
Revises: 7394fd3b630d
Create Date: 2025-07-04 18:00:32.658678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9244536033a'
down_revision = '7394fd3b630d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_bucket_file', 'files', ['bucket_name', 'file_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_bucket_file', 'files', type_='unique')
    # ### end Alembic commands ###
